# Generated by Django 4.2.7 on 2023-11-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='besicdata',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
