# Generated by Django 4.2.7 on 2023-11-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0003_alter_besicdata_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pic', models.ImageField(upload_to='Organizers/%Y/%m/%d/')),
                ('face_link', models.CharField(blank=True, max_length=125, null=True)),
                ('x_link', models.CharField(blank=True, max_length=125, null=True)),
                ('web_site', models.CharField(blank=True, max_length=125, null=True)),
                ('phone', models.CharField(blank=True, max_length=125, null=True)),
            ],
        ),
    ]
